spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.url=${MYSQL_URL:${DB_URL:jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:LMVhOEKLxWUrtVDJzLzSMyqHiHYuiMEX}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.address=0.0.0.0
server.port=${PORT:8070}

# Disable Default Error Page:
server.error.whitelabel.enabled=false

novabank.app.secret=${JWT_SECRET:helloDarknessMyOldFriendIComeToTalkWithYouAgain}
novabank.app.expires.in=${JWT_EXPIRES_IN:604800}
